version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      - PORT=3000
      - Mongo_url=mongodb+srv://muskanjain:<db_password>@cluster0.hgyvyuj.mongodb.net/?appName=Cluster0
      - JWT_Secret=7041771756e838066d47629c081258c81906c988
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend